cargo-features = ["workspace-inheritance"]

[package]
name = "foo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4.16", features = ["serde"] }
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.79"

